environment_tag = "ChaosStudioDemo"
owner_tag       = "dacat"
health_tag = "Active"
labname         = "chaos-demo"
uks         = "uksouth"
ukscode     = "uks"
# ukw         = "ukwest"
# ukwcode     = "ukw"
ukscidr     = "10.150.0.0/19"
# ukwcidr     = "10.160.0.0/19"
servercounta    = 1
servercountb    = 1
vmsscounta      = 2
uksaccounttier = "Standard"
uksart = "LRS"
uks-asp-os = "Linux"
uks-asp-sku = "B1"
days_to_expire = "7"
var.pipeline_sp_object_id = "b8fd7189-daa9-49de-854d-2dddac8ec22b"